# Generated by Django 5.2.3 on 2025-06-11 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('img', models.ImageField(upload_to='houses/')),
                ('type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House')], max_length=50)),
                ('Purpose', models.CharField(choices=[('rent', 'Rent'), ('sale', 'Sale')], max_length=50)),
                ('home_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('land', 'Land'), ('industrial', 'Industrial'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rooms', models.PositiveIntegerField()),
                ('bedrooms', models.PositiveIntegerField()),
                ('bathrooms', models.PositiveIntegerField()),
                ('sqft', models.PositiveIntegerField()),
                ('parking', models.BooleanField(default=False)),
                ('elevator', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'House',
                'verbose_name_plural': 'Houses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='houseFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airconditioning', models.BooleanField(default=False)),
                ('outdoor_kitchen', models.BooleanField(default=False)),
                ('basketball', models.BooleanField(default=False)),
                ('pool', models.BooleanField(default=False)),
                ('modern_kitchen', models.BooleanField(default=False)),
                ('balcony', models.BooleanField(default=False)),
                ('barbecue', models.BooleanField(default=False)),
                ('fireplace', models.BooleanField(default=False)),
                ('tennis_court', models.BooleanField(default=False)),
                ('refrigerator', models.BooleanField(default=False)),
                ('garage', models.BooleanField(default=False)),
                ('recration', models.BooleanField(default=False)),
                ('security', models.BooleanField(default=False)),
                ('network', models.BooleanField(default=False)),
                ('window_covering', models.BooleanField(default=False)),
                ('landscaping', models.BooleanField(default=False)),
                ('microwave', models.BooleanField(default=False)),
                ('indoor_game', models.BooleanField(default=False)),
                ('jacuzzi', models.BooleanField(default=False)),
                ('washer', models.BooleanField(default=False)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='core.house')),
            ],
            options={
                'verbose_name': 'House Feature',
                'verbose_name_plural': 'House Features',
                'ordering': ['house'],
            },
        ),
        migrations.CreateModel(
            name='houseGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='house_gallery/')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='core.house')),
            ],
            options={
                'verbose_name': 'House Gallery',
                'verbose_name_plural': 'House Galleries',
                'ordering': ['house'],
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='core.house')),
            ],
            options={
                'verbose_name': 'Inquiry',
                'verbose_name_plural': 'Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
